name: droptune
description: Droptune official application

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rounded_modal: ^1.0.0
  fluro: ^1.5.0
  flute_music_player:
  audioplayers: 0.10.1
  permission_handler: 2.1.2
  get_it: ^1.0.3
  sqflite: ^1.1.6
  provider: ^3.0.0+1
  shared_preferences: ^0.5.3+4
  media_notification: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/all_tracks.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/droptune_logo.png
    - assets/images/login_background.png
    - assets/images/droptune_logo_login.png
    - assets/images/default_song_image.jpg
    - assets/images/all_tracks.png
    - assets/images/add_playlist_button.png
    - assets/images/forward_button.png
    - assets/images/repeat_icon.png
    - assets/images/shuffle_icon.png
    - assets/images/pause_play_button.png
    - assets/images/the_razors_edge.png
    - assets/images/desync_icon.png
    - assets/images/sync_icon.png
    - assets/images/plus_icon.png
    - assets/images/rename_icon.png
    - assets/images/queue_icon.png
    - assets/images/remove_icon.png
    - assets/fonts/Poppins-Regular.ttf
    - assets/fonts/Poppins-Bold.ttf
    - assets/fonts/Poppins-Medium.ttf

  fonts:
  - family: Poppins
    fonts:
    - asset: assets/fonts/Poppins-Regular.ttf
    - asset: assets/fonts/Poppins-Medium.ttf
      weight: 300